services:
  - type: web
    name: heart-disease-predictor
    env: python
    plan: starter
    healthCheckPath: /health
    autoDeploy: true
    buildCommand: |
      # Update package list
      apt-get update
      
      # Install system dependencies including Tesseract OCR and Poppler
      apt-get install -y \
        tesseract-ocr \
        tesseract-ocr-eng \
        tesseract-ocr-osd \
        poppler-utils \
        libpoppler-cpp-dev \
        pkg-config \
        libcairo2-dev \
        libpango1.0-dev \
        libglib2.0-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libgif-dev \
        libwebp-dev \
        libopenjp2-7-dev \
        libtesseract-dev \
        libleptonica-dev
      
      # Install Python dependencies
      pip install -r requirements.txt
      
      # Verify Tesseract installation
      echo "Verifying Tesseract installation..."
      tesseract --version
      echo "Tesseract installation verified!"
    startCommand: python start_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false 